[package]
name = "raplrs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.23"
ncurses = "5.101.0"
csv = "1.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"